/**
 * atlas_data.js - Radiologický Obrazový Atlas pro studijní portál Radiologie
 * Autentické CT, MR, RTG, UZ a angiografické snímky s klinickými popisy a navigací.
 */

window.RADIOLKA_ATLAS = [
  {
    "id": "atlas-radio-1-1",
    "questionId": "radio-1",
    "topicTitle": "Princip rentgenky a RTG vyšetření",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "Schéma / Fyzika",
    "title": "Schéma rentgenky a vznik RTG záření",
    "caption": "Schéma vakuové diody (rentgenky) s rotující wolframovou anodou a žhavenou katodou emitující elektrony.",
    "src": "images/textbook/fig_p007__R47.jpg"
  },
  {
    "id": "atlas-radio-2-2",
    "questionId": "radio-2",
    "topicTitle": "Negativní biologické účinky ionizujícího záření a radiační ochrana",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "Fyzika / HU",
    "title": "Základní fyzikální principy & Denzity tkání",
    "caption": "Škála denzit tkání podle absorpce záření v radiologii od plynu (-1000 HU) přes vodu (0 HU) až po kost (+1000 HU).",
    "src": "images/anki/paste-d7d5eb34458b8b45e0d74d31575b2d9686f2be44.jpg"
  },
  {
    "id": "atlas-radio-3-3",
    "questionId": "radio-3",
    "topicTitle": "Princip ultrasonografického vyšetření (UZ)",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "UZ / Fyzika",
    "title": "Princip ultrazvuku a piezoelektrického měniče",
    "caption": "Generování a detekce ultrazvukových vln pomocí piezoelektrického krystalu a šíření akustického vlnění v tkáních.",
    "src": "images/textbook/fig_p010__R61.jpg"
  },
  {
    "id": "atlas-radio-4-4",
    "questionId": "radio-4",
    "topicTitle": "Princip výpočetní tomografie (CT)",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "CT",
    "title": "Hounsfieldova stupnice denzit na CT (HU)",
    "caption": "Škála denzit v Hounsfieldových jednotkách: Vzduch (-1000 HU), Tuk (-100 až -50 HU), Voda (0 HU), Měkké tkáně (+30 až +60 HU), Kompaktní kost (+1000 HU).",
    "src": "images/anki/paste-d7d5eb34458b8b45e0d74d31575b2d9686f2be44.jpg"
  },
  {
    "id": "atlas-radio-4-5",
    "questionId": "radio-4",
    "topicTitle": "Princip výpočetní tomografie (CT)",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "CT Schéma",
    "title": "Schéma multidetektorového spirálního CT",
    "caption": "Rotace rentgenky a oblouku polovodičových detektorů v gantry současně s plynulým posunem stolu pacienta.",
    "src": "images/textbook/fig_p011__R71.jpg"
  },
  {
    "id": "atlas-radio-5-6",
    "questionId": "radio-5",
    "topicTitle": "Princip magnetické rezonance (MR)",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "MR Schéma",
    "title": "Princip magnetické rezonance a relaxace protonů",
    "caption": "Orientace spinů vodíkových protonů v magnetickém poli B0, radiofrekvenční excitace a návrat do rovnováhy (T1 a T2 relaxace).",
    "src": "images/textbook/fig_p013__R81.jpg"
  },
  {
    "id": "atlas-radio-5-7",
    "questionId": "radio-5",
    "topicTitle": "Princip magnetické rezonance (MR)",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "CT vs MR",
    "title": "Srovnání CT a MR v diagnostice CNS",
    "caption": "Výhody a limitace CT vs. MR: CT exceluje v rychlosti a detekci akutního krvácení a kostí; MR má vynikající tkáňový kontrast pro měkké tkáně a časnou ischemii.",
    "src": "images/anki/paste-e641091bbe0f40394e16e595380f904c3dcbe3a8.jpg"
  },
  {
    "id": "atlas-radio-6-8",
    "questionId": "radio-6",
    "topicTitle": "Kontrastní látky – rozdělení, nežádoucí reakce, jejich prevence a léčba",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "Angiografie / KL",
    "title": "Kontrastní vyšetření cévního řečiště",
    "caption": "Aplikace neionické jodové kontrastní látky pro angiografické zobrazení tepenného řečiště a zhodnocení perfuze.",
    "src": "images/anki/paste-6ccb647992c2b53075e38ead51fa89fcad07aea7.jpg"
  },
  {
    "id": "atlas-radio-7-9",
    "questionId": "radio-7",
    "topicTitle": "Metody zobrazování hrudníku",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Normální skiagram hrudníku v PA projekci",
    "caption": "Přehledný snímek hrudníku: symetrické plicní křídla, ostré kostofrenické úhly, normální kardiotorakální index, trachea ve střední čáře.",
    "src": "images/anki/_1-normal-chest.jpg"
  },
  {
    "id": "atlas-radio-7-10",
    "questionId": "radio-7",
    "topicTitle": "Metody zobrazování hrudníku",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Schéma",
    "title": "Anatomické struktury na RTG hrudníku",
    "caption": "Rentgenová anatomie hrudníku: plicní hily, cévní kresba, tracheobronchiální strom, srdeční oddíly a kontury bránice.",
    "src": "images/textbook/fig_p028__R145.jpg"
  },
  {
    "id": "atlas-radio-8-11",
    "questionId": "radio-8",
    "topicTitle": "Obecná RTG symptomatologie onemocnění plic",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Atelektáza pravého horního laloku (Golden S sign)",
    "caption": "Kolaps horního laloku způsobený centrálním nádorem zvedá horizontální fisuru vzhůru a mediodorzálně, tvoříc typický tvar písmene S (Goldenovo S).",
    "src": "images/anki/right-upper-lobe-collapse-9.jpg"
  },
  {
    "id": "atlas-radio-8-12",
    "questionId": "radio-8",
    "topicTitle": "Obecná RTG symptomatologie onemocnění plic",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Alveolární konsolidace a vzdušný bronchogram",
    "caption": "Alveolární syndrom při krupózní pneumonii: homogenní zastínění laloku s patrným vzdušným bronchogramem (projasněné průdušky zalité tekutinou).",
    "src": "images/textbook/fig_p035__R175.jpg"
  },
  {
    "id": "atlas-radio-9-13",
    "questionId": "radio-9",
    "topicTitle": "Nádory plic a bronchogenní karcinom",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Centrální bronchogenní karcinom s atelektázou",
    "caption": "Centrálně rostoucí tumor v pravém hilu vedoucí k obstrukci bronchu a následné resorpční atelektáze laloku.",
    "src": "images/textbook/fig_p039__R194.jpg"
  },
  {
    "id": "atlas-radio-9-14",
    "questionId": "radio-9",
    "topicTitle": "Nádory plic a bronchogenní karcinom",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "Algoritmus / CT",
    "title": "Algoritmus stagingu nemalobuněčného karcinomu plic (NSCLC)",
    "caption": "Kontrastní CT hrudníku a horního břicha doplněné o PET/CT a MR mozku k přesnému stanovení T, N a M stádia onemocnění.",
    "src": "images/anki/paste-e1a88010bc62a07a123629546b7d7eb6e0c53f55.jpg"
  },
  {
    "id": "atlas-radio-10-15",
    "questionId": "radio-10",
    "topicTitle": "Nádory a expanze mediastina",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG / CT",
    "title": "Expanzivní léze předního mediastina",
    "caption": "Zastínění předního mediastina rozšiřující horní mediastinální stín na RTG a CT (dif. dg. lymfom, thymom, retrosternální struma).",
    "src": "images/textbook/fig_p039__R195.jpg"
  },
  {
    "id": "atlas-radio-11-16",
    "questionId": "radio-11",
    "topicTitle": "Onemocnění pleurálních prostorů (výpotek, pneumotorax, mezoteliom)",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Pleurální výpotek – otupení pravého kostofrenického úhlu",
    "caption": "Typický nález tekutiny v pleurální dutině na vestoje zhotoveném snímku: tekutina stoupá po laterální hrudní stěně a vytváří konkávní meniskus.",
    "src": "images/anki/small-right-pleural-effusion.jpg"
  },
  {
    "id": "atlas-radio-11-17",
    "questionId": "radio-11",
    "topicTitle": "Onemocnění pleurálních prostorů (výpotek, pneumotorax, mezoteliom)",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník (vleže)",
    "title": "Pleurální výpotek na snímku vleže (Supine)",
    "caption": "U ležícího pacienta se tekutina rozlévá dorzálně, což se projevuje difuzním závojem hemitoraxu se zachovanou cévní kresbou bez menisku.",
    "src": "images/anki/pleural-effusion-supine.JPG"
  },
  {
    "id": "atlas-radio-11-18",
    "questionId": "radio-11",
    "topicTitle": "Onemocnění pleurálních prostorů (výpotek, pneumotorax, mezoteliom)",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Pneumotorax s kolapsem plicního křídla",
    "caption": "Pneumotorax: linie viscerální pleury, za kterou zcela chybí plicní cévní kresba (avaskulární zóna) a dochází k retrakci plicního parenchymu k hilu.",
    "src": "images/textbook/fig_p051__R252.jpg"
  },
  {
    "id": "atlas-radio-12-19",
    "questionId": "radio-12",
    "topicTitle": "Analýza srdečního stínu na RTG a metody kardiální radiologie",
    "section": "Hrudník a srdce",
    "category": "Kardio",
    "modality": "RTG Hrudník",
    "title": "Kardiomegalie na RTG snímku hrudníku",
    "caption": "Kardiotorakální index (KTI) > 0.50 na PA snímku – výrazné zvětšení srdečního stínu přesahující polovinu šířky hrudního koše (cor bovinum).",
    "src": "images/anki/cardiomegaly-3.jpg"
  },
  {
    "id": "atlas-radio-12-20",
    "questionId": "radio-12",
    "topicTitle": "Analýza srdečního stínu na RTG a metody kardiální radiologie",
    "section": "Hrudník a srdce",
    "category": "Kardio",
    "modality": "RTG Schéma",
    "title": "Normální srdeční kontury a segmenty na PA skiagramu",
    "caption": "Pravý okraj srdečního stínu (horní dutá žíla, pravá síň) a levý okraj (aortální knoflík, plicnice, ouško levé síně, levá komora).",
    "src": "images/textbook/fig_p062__R309.jpg"
  },
  {
    "id": "atlas-radio-13-21",
    "questionId": "radio-13",
    "topicTitle": "Proměny srdečního stínu při chlopenních vadách a srdečním selhání",
    "section": "Hrudník a srdce",
    "category": "Kardio",
    "modality": "RTG Srdce",
    "title": "Mitrální konfigurace srdce (zvětšení levé síně)",
    "caption": "Zvětšení levé síně při mitrální vadě: narovnání levého srdečního okraje (vyklenutí ouška), elevace levého hlavního bronchu a dvojitý stín na pravém okraji.",
    "src": "images/textbook/fig_p064__R322.jpg"
  },
  {
    "id": "atlas-radio-14-22",
    "questionId": "radio-14",
    "topicTitle": "Normální a patologická plicní vaskularizace (plicní edém, embolie, hypertenze)",
    "section": "Hrudník a srdce",
    "category": "Kardio",
    "modality": "CT Angiografie",
    "title": "CT angiografie při suspektní plicní embolii (PE)",
    "caption": "Zlatý standard v diagnostice PE: kontrastní CT plicnice spolehlivě zobrazuje intraluminální defekty v náplni (tromby) v hlavních, lobárních i segmentálních větvích.",
    "src": "images/anki/paste-7f9baf293ef81c8ed42a1121f636013e8450732c.jpg"
  },
  {
    "id": "atlas-radio-14-23",
    "questionId": "radio-14",
    "topicTitle": "Normální a patologická plicní vaskularizace (plicní edém, embolie, hypertenze)",
    "section": "Hrudník a srdce",
    "category": "Kardio",
    "modality": "RTG Hrudník",
    "title": "Plicní edém a městnání – Kerleyovy B linie a motýlí křídla",
    "caption": "Rentgenový obraz městnání při levostranném selhání: redistribuce krve do horních polí, peribronchiální prosáknutí, Kerley B linie a perihilární alveolární plicní edém.",
    "src": "images/textbook/fig_p068__R348.jpg"
  },
  {
    "id": "atlas-radio-15-24",
    "questionId": "radio-15",
    "topicTitle": "Metody zobrazování trávicí trubice (jícen, žaludek, střevo)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Břicho",
    "title": "Nativní snímek břicha – ileózní stav tenkého střeva",
    "caption": "Klasický rentgenový obraz distenze kliček tenkého střeva s nápadnými plicae circulares (řasami) a hladinkami plynu/tekutiny.",
    "src": "images/anki/small-bowel-obstruction-15.jpg"
  },
  {
    "id": "atlas-radio-16-25",
    "questionId": "radio-16",
    "topicTitle": "RTG obrazy patologických stavů trávicí trubice (záněty, vředy, divertikly, nádory)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "Algoritmus / GIT",
    "title": "Diagnostický algoritmus u krvácení z dolního GIT",
    "caption": "Vyšetřovací postup při enteroragii: kolonoskopie, CTA břicha k detekci aktivní extravazace kontrastní látky (> 0.5 ml/min) a selektivní angiografie.",
    "src": "images/anki/paste-a5bd11be02a976414158fc8e6d5e9b1afcfadab9.jpg"
  },
  {
    "id": "atlas-radio-17-26",
    "questionId": "radio-17",
    "topicTitle": "Zobrazování náhlých příhod břišních (NPB)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Hrudník/Břicho",
    "title": "Pneumoperitoneum – volný plyn pod bránicí vestoje",
    "caption": "Srpkovité projasnění volného vzduchu pod pravou klenbou bránice oddělující bránici od jater při perforaci dutého orgánu.",
    "src": "images/anki/pneumoperitoneum-12.jpg"
  },
  {
    "id": "atlas-radio-17-27",
    "questionId": "radio-17",
    "topicTitle": "Zobrazování náhlých příhod břišních (NPB)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Břicho",
    "title": "Riglerův příznak (Double wall sign) na RTG břicha vleže",
    "caption": "Riglerův znak: plynová náplň uvnitř i vně střevní kličky způsobuje, že je střevní stěna ostře ohraničena z obou stran.",
    "src": "images/anki/pneumoperitoneum-child.png"
  },
  {
    "id": "atlas-radio-17-28",
    "questionId": "radio-17",
    "topicTitle": "Zobrazování náhlých příhod břišních (NPB)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Břicho",
    "title": "Mechanický ileus tenkého střeva – pravidlo 3-6-9",
    "caption": "Dilatace tenkého střeva nad 3 cm, tračníku nad 6 cm a céka nad 9 cm svědčí pro obstrukci střevního lumina.",
    "src": "images/anki/small-bowel-obstruction-15.jpg"
  },
  {
    "id": "atlas-radio-17-29",
    "questionId": "radio-17",
    "topicTitle": "Zobrazování náhlých příhod břišních (NPB)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "UZ / CT",
    "title": "Akutní apendicitida a bolest v pravém podbřišku",
    "caption": "Diagnostika akutní apendicitidy: UZ jako metoda 1. volby u dětí a mladých pacientů (aperistaltický terčovitý útvar > 6 mm), kontrastní CT u dospělých.",
    "src": "images/anki/paste-3ff058e374b992338cc167b53603ba6978944365.jpg"
  },
  {
    "id": "atlas-radio-18-30",
    "questionId": "radio-18",
    "topicTitle": "Zobrazování onemocnění jater (cysty, hemangiom, FNH, adenom, HCC, metastázy)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "UZ Játra",
    "title": "Ultrazvukové vyšetření hepatobiliární oblasti",
    "caption": "Ultrasonografie pravého podžebří: zhodnocení jaterního parenchymu, žlučníku, intra- a extrahepatálních žlučovodů a portální žíly.",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-19-31",
    "questionId": "radio-19",
    "topicTitle": "Zobrazování onemocnění portálního řečiště a portální hypertenze",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "CT Angiografie",
    "title": "Zobrazení mezenteriálního a portálního cévního řečiště",
    "caption": "Kontrastní CT angiografie a portální fáze pro průkaz vaskulárních okluzí, kolaterálního řečiště a patologií mezenteriálních cév.",
    "src": "images/anki/paste-b5cd2e1654228a7421b2fcf8f46d5ea4dfe463e8.jpg"
  },
  {
    "id": "atlas-radio-20-32",
    "questionId": "radio-20",
    "topicTitle": "Zobrazování onemocnění žlučníku a žlučových cest (cholelitiáza, cholecystitida, ikterus)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "UZ Žlučník",
    "title": "Ultrazvuk žlučníku – cholelitiáza a cholecystitida",
    "caption": "Hyperechogenní konkrement s distálním akustickým stínem v lumen žlučníku, prosáknutí a ztluštění stěny žlučníku > 3 mm při zánětu.",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-21-33",
    "questionId": "radio-21",
    "topicTitle": "Zobrazování onemocnění pankreatu (akutní a chronická pankreatitida, adenokarcinom, NET)",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "CT Pankreas",
    "title": "Pankreatobiliární diagnostika a zobrazení pankreatu",
    "caption": "Protokol kontrastního CT s tenkými řezy v pankreatické a portální fázi pro staging tumorů hlavy pankreatu a zhodnocení cévních invazí.",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-22-34",
    "questionId": "radio-22",
    "topicTitle": "Metody zobrazování ledvin a odvodných močových cest",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "UZ Ledvina",
    "title": "Ultrazvukové zobrazení parenchymu a kalichopánvičkového systému ledviny",
    "caption": "Podélný řez ledvinou: echogenita kůry nižší než jaterní parenchym, hypoechogenní pyramidy dřeně a hyperechogenní centrální sinus.",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-23-35",
    "questionId": "radio-23",
    "topicTitle": "Zobrazování ložiskových a difuzních onemocnění ledvin",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "CT / UZ",
    "title": "Klasifikace renálních cyst podle Bosniaka",
    "caption": "Kategorií I-II (jednoduché nekomplikované cysty, beningní) až IV (cystický karcinom s tlustými nodulárními septy a sycením po KL).",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-24-36",
    "questionId": "radio-24",
    "topicTitle": "Zobrazování onemocnění odvodných močových cest (urolitiáza, uoteliální nádory)",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "CT Urologie",
    "title": "Low-dose CT u renální koliky (Nekontrastní CT)",
    "caption": "Nízkodávkové nativní CT spolehlivě detekuje i drobné konkrementy v celém průběhu močovodu (včetně rtg nekontrastních urátových kamenů).",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-25-37",
    "questionId": "radio-25",
    "topicTitle": "Zobrazování onemocnění mužských pohlavních orgánů (prostata, varlata, skrotum)",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "MR Prostata",
    "title": "Multiparametrická MR prostaty (PI-RADS)",
    "caption": "mpMRI prostaty kombinující T2W, difuzní vážení (DWI/ADC) a dynamické postkontrastní sycení (DCE) k detekci klinicky významného karcinomu.",
    "src": "images/anki/paste-0aa7fc337dee405a258dc678221f2dcb8de74f7b.jpg"
  },
  {
    "id": "atlas-radio-26-38",
    "questionId": "radio-26",
    "topicTitle": "Zobrazování onemocnění ženských pohlavních orgánů a zobrazování v těhotenství",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "UZ Gynekologie",
    "title": "Ultrazvukové vyšetření v 1. trimestru těhotenství",
    "caption": "Lokalizace gestačního váčku v děložní dutině, průkaz vitality plodu (srdeční akce) a vyloučení ektopické gravidity při vaginálním krvácení.",
    "src": "images/anki/paste-db884d5302960b7b8d342e334644715ca469c715.jpg"
  },
  {
    "id": "atlas-radio-26-39",
    "questionId": "radio-26",
    "topicTitle": "Zobrazování onemocnění ženských pohlavních orgánů a zobrazování v těhotenství",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "Algoritmus / UZ",
    "title": "Algoritmus zobrazení pánevní bolesti u žen",
    "caption": "Transvaginální a transabdominální ultrazvuk jako metoda 1. volby pro odlišení gynekologických příčin (adnexitida, torze ovaria, ruptura cysty).",
    "src": "images/anki/paste-6e3ccfe564db2cdf0b7811012dd791b2a5c0546c.jpg"
  },
  {
    "id": "atlas-radio-27-40",
    "questionId": "radio-27",
    "topicTitle": "Zobrazování onemocnění prsu (mamografie, UZ, MR prsů)",
    "section": "Urogenitální trakt",
    "category": "Urogenitál",
    "modality": "Mamografie / UZ",
    "title": "Algoritmus senologické diagnostiky",
    "caption": "Kombinace mamografie (nad 45 let screening) a doplňující ultrasonografie u denzní prsní žlázy, indikace duktografie a MR prsů.",
    "src": "images/anki/paste-cc4023c7da7427372ea70437359d528082cd8811.jpg"
  },
  {
    "id": "atlas-radio-28-41",
    "questionId": "radio-28",
    "topicTitle": "Obecné projevy kostních onemocnění v RTG obraze",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "RTG Skelet",
    "title": "Typické projevy skeletální léze a periostu na RTG",
    "caption": "Hodnocení kortikalis, periostálních apozic, spongiózy a okolních měkkých tkání na standardním skiagramu.",
    "src": "images/anki/supracondylar-fracture-marked-displacement.jpg"
  },
  {
    "id": "atlas-radio-29-42",
    "questionId": "radio-29",
    "topicTitle": "Zobrazování kostních a kloubních zánětů (osteomyelitida, artritida, spondylodiscitida)",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "RTG / MR",
    "title": "Vyšetřovací postup při zánětlivém a traumatickém postižení kloubů",
    "caption": "Nativní RTG zachytí změny na kosti až po 10-14 dnech; MR je metodou volby pro časný záchyt zánětu a edému kostní dřeně (STIR/T2).",
    "src": "images/anki/paste-fe5ce9834defd3462f6d170d2d85d68a62bfc12f.jpg"
  },
  {
    "id": "atlas-radio-30-43",
    "questionId": "radio-30",
    "topicTitle": "Zobrazování kostních nádorů (benigní, maligní a metastázy)",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "RTG Skelet",
    "title": "Kostní léze – hodnocení zóny přechodu a periostální reakce",
    "caption": "Ostrá sklerotická zóna přechodu značí benigní pomalý růst; neostrá široká zóna s lytickým rozpadem kortikalis a periostální reakcí svědčí pro malignitu.",
    "src": "images/anki/supracondylar-fracture-marked-displacement.jpg"
  },
  {
    "id": "atlas-radio-31-44",
    "questionId": "radio-31",
    "topicTitle": "Obecné projevy kloubních onemocnění v RTG obraze",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "RTG Kloub",
    "title": "Zobrazení kloubní štěrbiny a přilehlých kostních struktur",
    "caption": "Rentgenové hodnocení kongruence kloubních ploch, šíře kloubní štěrbiny a přítomnosti osteofytů a subchondrálních změn.",
    "src": "images/anki/paste-c3d28255480bc814d768b0d16ec240fbc554836d.jpg"
  },
  {
    "id": "atlas-radio-32-45",
    "questionId": "radio-32",
    "topicTitle": "Zobrazování degenerativních a zánětlivých onemocnění kloubů (artróza, revmatoidní artritida, dna)",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "RTG Kloub",
    "title": "Degenerativní změny kloubů – Gonartróza",
    "caption": "Asymetrické zúžení kloubní štěrbiny, subchondrální osteoskleróza zátěžových ploch, tvorba marginálních osteofytů a subchondrálních geod.",
    "src": "images/anki/paste-c3d28255480bc814d768b0d16ec240fbc554836d.jpg"
  },
  {
    "id": "atlas-radio-33-46",
    "questionId": "radio-33",
    "topicTitle": "Zobrazování traumat kostí a kloubů (zlomeniny, dislokace, luxace, hojení)",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "RTG Traumatologie",
    "title": "Suprakondylická fraktura humeru s dislokací",
    "caption": "Dislokovaná suprakondylická fraktura u dětského pacienta: hodnocení přední humerální linie a radiokapitelární linie na bočném snímku.",
    "src": "images/anki/supracondylar-fracture-marked-displacement.jpg"
  },
  {
    "id": "atlas-radio-33-47",
    "questionId": "radio-33",
    "topicTitle": "Zobrazování traumat kostí a kloubů (zlomeniny, dislokace, luxace, hojení)",
    "section": "Muskuloskeletální systém",
    "category": "Skelet",
    "modality": "Trauma Protokol",
    "title": "Zobrazovací protokol u těžkého traumatu a polytraumatu",
    "caption": "Pravidlo dvou projekcí u končetinových traumat a celotělové polytrauma CT (pancan) u hemodynamicky stabilizovaného pacienta.",
    "src": "images/anki/paste-cbb4b89338f6d179a97599aadf5ea4782a3a6f08.jpg"
  },
  {
    "id": "atlas-radio-34-48",
    "questionId": "radio-34",
    "topicTitle": "Zobrazovací metody v neuroradiologii (CT, MR mozku, sekvence)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "MR / CT Mozek",
    "title": "Normální anatomie mozku na axiálním řezu MR a CT",
    "caption": "Axiální zobrazení mozku: bazální ganglia, capsula interna, postranní komory, kortikální sulci a rozhraní šedé a bílé hmoty.",
    "src": "images/anki/paste-362aa74dc191e102c19a92b3fdfc22188ec847db.jpg"
  },
  {
    "id": "atlas-radio-34-49",
    "questionId": "radio-34",
    "topicTitle": "Zobrazovací metody v neuroradiologii (CT, MR mozku, sekvence)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "Neuroradiologie",
    "title": "Indikační kritéria CT vs. MR v neuroradiologii",
    "caption": "CT jako 1. volba u akutních stavů (trauma, podezření na krvácení); MR pro detailní posouzení mozkového parenchymu, nádorů a demyelinizačních onemocnění.",
    "src": "images/anki/paste-e641091bbe0f40394e16e595380f904c3dcbe3a8.jpg"
  },
  {
    "id": "atlas-radio-35-50",
    "questionId": "radio-35",
    "topicTitle": "Zobrazování ischemických cévních mozkových příhod a možnosti léčby",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "Iktový Protokol / CT",
    "title": "Protokol akutního iktového zobrazení (Akutní iktový protokol)",
    "caption": "Tříkrokový protokol: 1. Nativní CT (vyloučení krvácení a časné známky), 2. CTA (okluze velké tepny), 3. Perfuzní CT (poměr penumbra / infarktové jádro pro trombektomii).",
    "src": "images/anki/F4.large_1597975591721.jpg"
  },
  {
    "id": "atlas-radio-35-51",
    "questionId": "radio-35",
    "topicTitle": "Zobrazování ischemických cévních mozkových příhod a možnosti léčby",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "MR Mozek (FLAIR)",
    "title": "Chronické ischemické vaskulární změny bílé hmoty",
    "caption": "Hyperintenzity periventrikulární bílé hmoty na T2/FLAIR (leukoencefalopatie, lakunární postižení při chronické mikroangiopatii).",
    "src": "images/anki/paste-3ceb552647df7b89f1bd8157343b7feba4de57bd.jpg"
  },
  {
    "id": "atlas-radio-36-52",
    "questionId": "radio-36",
    "topicTitle": "Zobrazování hemoragických cévních mozkových příhod (intracerebrální krvácení, SAK, aneurysmata)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT Mozek",
    "title": "Subarachnoidální krvácení (SAK) na nativním CT mozku",
    "caption": "Hyperdenzní krev vyplňující bazální cisterny a sulci hemisfér v oblasti Willisova okruhu při ruptuře intrakraniálního aneurysmatu.",
    "src": "images/anki/paste-91323fbd2d94cee5e82c217d22c687fc820f9203.jpg"
  },
  {
    "id": "atlas-radio-36-53",
    "questionId": "radio-36",
    "topicTitle": "Zobrazování hemoragických cévních mozkových příhod (intracerebrální krvácení, SAK, aneurysmata)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "Algoritmus SAK",
    "title": "Diagnostický algoritmus suspektního SAK",
    "caption": "Při podezření na SAK: akutní nativní CT; při negativitě lumbální punkce (spektrofotometrie); při pozitivitě CTA/DSA k nalezení zdroje krvácení.",
    "src": "images/anki/p451-f1.gif"
  },
  {
    "id": "atlas-radio-37-54",
    "questionId": "radio-37",
    "topicTitle": "Zobrazování kraniocerebrálních poranění (epidurální a subdurální hematom, kontuze, edém)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT Mozek",
    "title": "Epidurální vs. Subdurální hematom na CT",
    "caption": "Epidurální hematom: bikonvexní (čočkovitý) tvar ohraničený lebečními švy. Subdurální hematom: srpkovitý tvar kopírující hemisféru volně překračující švy.",
    "src": "images/anki/paste-73a97780f485776cbbe56e2b39caf6f5d4c65989.jpg"
  },
  {
    "id": "atlas-radio-37-55",
    "questionId": "radio-37",
    "topicTitle": "Zobrazování kraniocerebrálních poranění (epidurální a subdurální hematom, kontuze, edém)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT Mozek",
    "title": "Subfalcinní mozková herniace a intrakraniální hypertenze",
    "caption": "Masivní expanzivní efekt hematomu s přetlačením středočárových struktur (midline shift), kompresí postranní komory a subfalcinní herniací pod falx cerebri.",
    "src": "images/anki/subfalcine-herniation-ctisus-arrow-high.jpg"
  },
  {
    "id": "atlas-radio-38-56",
    "questionId": "radio-38",
    "topicTitle": "Zobrazování intrakraniálních nádorů (gliomy, meningeomy, vestibulární schwannom, metastázy)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "MR Mozek",
    "title": "Zobrazení intrakraniálních expanzí na kontrastní MR",
    "caption": "MR s podáním gadoliniové kontrastní látky v T1 vážení je zlatým standardem pro přesné ohraničení tumoru, průkaz sycení a posouzení operability.",
    "src": "images/anki/paste-e641091bbe0f40394e16e595380f904c3dcbe3a8.jpg"
  },
  {
    "id": "atlas-radio-38-57",
    "questionId": "radio-38",
    "topicTitle": "Zobrazování intrakraniálních nádorů (gliomy, meningeomy, vestibulární schwannom, metastázy)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT / MR Mozek",
    "title": "Expanzivní léze s perifokálním edémem a útlakem komor",
    "caption": "Typický vazogenní edém v bílé hmotě v okolí maligního tumoru vedoucí k útlaku mozkových komor a herniacím.",
    "src": "images/anki/subfalcine-herniation-ctisus-arrow-high.jpg"
  },
  {
    "id": "atlas-radio-39-58",
    "questionId": "radio-39",
    "topicTitle": "Zobrazování zánětů CNS a demyelinizačních onemocnění (roztroušená skleróza, encefalitida, absces)",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "MR Mozek (FLAIR)",
    "title": "Léze bílé hmoty mozku na FLAIR a T2 sekvencích",
    "caption": "Periventrikulární a juxtakortikální hyperintenzity typické pro demyelinizační plaky roztroušené sklerózy orientované kolmo na komory (Dawsonovy prsty).",
    "src": "images/anki/paste-3ceb552647df7b89f1bd8157343b7feba4de57bd.jpg"
  },
  {
    "id": "atlas-radio-40-59",
    "questionId": "radio-40",
    "topicTitle": "Zobrazování úrazů páteře a míchy",
    "section": "Neuroradiologie a páteř",
    "category": "Páteř",
    "modality": "CT Páteř",
    "title": "Indikační kritéria pro CT krční páteře po traumatu (NEXUS)",
    "caption": "Multidetektorové tenkořezové CT krční páteře s multiplanárními rekonstrukcemi (MPR) je metodou 1. volby u traumat podle kritérií NEXUS a Canadian C-Spine Rule.",
    "src": "images/anki/paste-72d835032c024772b0b3c6d348eb404b7129f4b2.jpg"
  },
  {
    "id": "atlas-radio-40-60",
    "questionId": "radio-40",
    "topicTitle": "Zobrazování úrazů páteře a míchy",
    "section": "Neuroradiologie a páteř",
    "category": "Páteř",
    "modality": "RTG Páteř",
    "title": "Hodnocení 4 linií krční páteře na bočném snímku",
    "caption": "Čtyři paralelní linie: přední vertebrální linie, zadní vertebrální linie, spinolaminární linie a linie trnových výběžků pro odhalení subluxací.",
    "src": "images/anki/paste-84af1659341da9978a022d9ac34fa0de22790268.jpg"
  },
  {
    "id": "atlas-radio-41-61",
    "questionId": "radio-41",
    "topicTitle": "Degenerativní onemocnění páteře (herniace disku, spinální stenóza, spondylóza)",
    "section": "Neuroradiologie a páteř",
    "category": "Páteř",
    "modality": "RTG / MR Páteř",
    "title": "Degenerativní změny obratlů a meziobratlových prostorů",
    "caption": "Snížení meziobratlové ploténky, subchondrální skleróza krycích ploch obratlových těl a tvorba ventrálních i dorzálních osteofytů.",
    "src": "images/anki/paste-84af1659341da9978a022d9ac34fa0de22790268.jpg"
  },
  {
    "id": "atlas-radio-42-62",
    "questionId": "radio-42",
    "topicTitle": "Zobrazování nádorů páteře a míchy",
    "section": "Neuroradiologie a páteř",
    "category": "Páteř",
    "modality": "Intervence / RTG",
    "title": "Perkutánní vertebroplastika u patologických fraktur obratlů",
    "caption": "Intervenční aplikace kostního cementu (PMMA) pod skiaskopickou kontrolou do těla obratle zničeného metastázou nebo osteoporózou.",
    "src": "images/anki/percutaneous-vertebroplasty (1).jpg"
  },
  {
    "id": "atlas-radio-43-63",
    "questionId": "radio-43",
    "topicTitle": "Možnosti invazivního a neinvazivního zobrazování cév (UZ, CTA, MRA, DSA)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "Angiografie",
    "title": "Neinvazivní a invazivní zobrazení karotického řečiště",
    "caption": "Srovnání dopplerovské sonografie, kontrastní CTA a DSA v kvantifikaci stenóz karotid (NASCET kritéria).",
    "src": "images/anki/paste-6ccb647992c2b53075e38ead51fa89fcad07aea7.jpg"
  },
  {
    "id": "atlas-radio-44-64",
    "questionId": "radio-44",
    "topicTitle": "Příprava nemocného před angiografií a péče po výkonu",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "RTG / Přístup",
    "title": "Zajištění cévního přístupu a ověření polohy katetru",
    "caption": "Správná poloha centrálního katetru v dolní třetině horní duté žíly (SVC) ověřená skiagrafií/skiaskopií.",
    "src": "images/anki/picc-line-2.jpg"
  },
  {
    "id": "atlas-radio-45-65",
    "questionId": "radio-45",
    "topicTitle": "Základní patologické nálezy při angiografii (stenózy, uzávěry, aneuryzmata, disekce)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "DSA / Patologie",
    "title": "Angiografický nález kritické stenózy arterie",
    "caption": "Koncentrické zúžení lumina tepny se zpožděným tokem a poststenotickou dilatací na digitální subtrakční angiografii.",
    "src": "images/anki/paste-6ccb647992c2b53075e38ead51fa89fcad07aea7.jpg"
  },
  {
    "id": "atlas-radio-46-66",
    "questionId": "radio-46",
    "topicTitle": "Transluminální remodelace cév (PTA, stentování, trombektomie)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "Vaskulární Intervence",
    "title": "Perkutánní transluminální angioplastika (PTA) a stenting",
    "caption": "Zavedení balónkového katetru a implantace kovového stentu do místa stenózy s plným obnovením průsvitu cévy.",
    "src": "images/anki/paste-6ccb647992c2b53075e38ead51fa89fcad07aea7.jpg"
  },
  {
    "id": "atlas-radio-47-67",
    "questionId": "radio-47",
    "topicTitle": "Endovaskulární embolizace (materiály, indikace, krvácení, tumory)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "Embolizace / Intervence",
    "title": "Superselektivní katetrizace a terapeutická embolizace",
    "caption": "Zavedení mikrokatetru do krvácející tepenné větve a okluze cévního lumen spirálami k okamžitému zastavení krvácení.",
    "src": "images/anki/paste-a5bd11be02a976414158fc8e6d5e9b1afcfadab9.jpg"
  },
  {
    "id": "atlas-radio-48-68",
    "questionId": "radio-48",
    "topicTitle": "Nevaskulární intervenční metody (drenáže, biopsie, vertebroplastika, RFA)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "Nevaskulární Intervence",
    "title": "Perkutánní vertebroplastika pod skiaskopickou navigací",
    "caption": "Zavedení trokaru transpedikulárně do kolabovaného obratlového těla a aplikace PMMA cementu pro stabilizaci a úlevu od bolesti.",
    "src": "images/anki/percutaneous-vertebroplasty (1).jpg"
  },
  {
    "id": "atlas-radio-49-69",
    "questionId": "radio-49",
    "topicTitle": "Zobrazování onemocnění žilního systému (hluboká žilní trombóza, varixy, syndrom HDŽ)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "Venografie / RTG",
    "title": "Zobrazení horní duté žíly a centrálního žilního řečiště",
    "caption": "Skiagrafické a venografické zhodnocení průchodnosti centrálních žil a vyloučení trombózy či zúžení horní duté žíly.",
    "src": "images/anki/picc-line-2.jpg"
  },
  {
    "id": "atlas-radio-50-70",
    "questionId": "radio-50",
    "topicTitle": "Zobrazování onemocnění lymfatického systému (lymfadenopatie, lymfomy, lymfedém)",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "PET/CT / Lymfatika",
    "title": "PET/CT a CT staging lymfadenopatie a lymfomů",
    "caption": "Kombinované PET/CT zobrazení metabolismu glukózy (18F-FDG) a anatomického CT pro přesné určení zasažených lymfatických uzlin a monitoraci léčby.",
    "src": "images/anki/paste-e1a88010bc62a07a123629546b7d7eb6e0c53f55.jpg"
  },
  {
    "id": "atlas-extra-1",
    "questionId": "radio-37",
    "topicTitle": "Zobrazování kraniocerebrálních poranění",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT Mozek",
    "title": "Epidurální vs. Subdurální hematom (Srovnání)",
    "caption": "Epidurální hematom je bikonvexní (čočkovitý) a nepřekračuje lebeční švy. Subdurální hematom je srpkovitý a volně překračuje sutury podél hemisféry.",
    "src": "images/anki/paste-73a97780f485776cbbe56e2b39caf6f5d4c65989.jpg"
  },
  {
    "id": "atlas-extra-2",
    "questionId": "radio-36",
    "topicTitle": "Zobrazování hemoragických cévních mozkových příhod",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT Mozek",
    "title": "Subarachnoidální krvácení (SAK)",
    "caption": "Hyperdenzní krev vyplňující bazální cisterny, sulci a fisury mozku při ruptuře intrakraniálního aneurysmatu Willisova okruhu.",
    "src": "images/anki/paste-91323fbd2d94cee5e82c217d22c687fc820f9203.jpg"
  },
  {
    "id": "atlas-extra-3",
    "questionId": "radio-17",
    "topicTitle": "Zobrazování náhlých příhod břišních",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Hrudník/Břicho",
    "title": "Pneumoperitoneum (Srpkovitý plyn pod bránicí)",
    "caption": "Volný plyn v peritoneální dutině viditelný jako tenký srpkovitý proužek pod pravou klenbou bránice vestoje.",
    "src": "images/anki/pneumoperitoneum-12.jpg"
  },
  {
    "id": "atlas-extra-4",
    "questionId": "radio-17",
    "topicTitle": "Zobrazování náhlých příhod břišních",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Břicho",
    "title": "Riglerův příznak (Double Wall Sign)",
    "caption": "Riglerův znak při pneumoperitoneu vleže: plynová náplň zevnitř i zvenčí střevní kličky ostře vizualizuje celou střevní stěnu.",
    "src": "images/anki/pneumoperitoneum-child.png"
  },
  {
    "id": "atlas-extra-5",
    "questionId": "radio-15",
    "topicTitle": "Metody zobrazování trávicí trubice",
    "section": "Břicho a trávicí trakt",
    "category": "Břicho",
    "modality": "RTG Břicho",
    "title": "Mechanický ileus tenkého střeva (Hladinky)",
    "caption": "Distendované kličky tenkého střeva s nápadnými cirkulárními řasami a hydroaerickými hladinkami (pravidlo 3-6-9).",
    "src": "images/anki/small-bowel-obstruction-15.jpg"
  },
  {
    "id": "atlas-extra-6",
    "questionId": "radio-11",
    "topicTitle": "Onemocnění pleurálních prostorů",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Pleurální výpotek (Otupení kostofrenického úhlu)",
    "caption": "Meniskový znak tekutiny v pravém kostofrenickém úhlu na vzpřímeném PA skiagramu hrudníku.",
    "src": "images/anki/small-right-pleural-effusion.jpg"
  },
  {
    "id": "atlas-extra-7",
    "questionId": "radio-8",
    "topicTitle": "Obecná RTG symptomatologie onemocnění plic",
    "section": "Hrudník a srdce",
    "category": "Hrudník",
    "modality": "RTG Hrudník",
    "title": "Atelektáza horního laloku (Golden S sign)",
    "caption": "Kolaps pravého horního laloku s elevací horizontální fisury tvořící typický Goldenův S znak při centrálním nádoru.",
    "src": "images/anki/right-upper-lobe-collapse-9.jpg"
  },
  {
    "id": "atlas-extra-8",
    "questionId": "radio-12",
    "topicTitle": "Analýza srdečního stínu",
    "section": "Hrudník a srdce",
    "category": "Kardio",
    "modality": "RTG Hrudník",
    "title": "Kardiomegalie (Kardiotorakální index > 0.5)",
    "caption": "Výrazné zvětšení srdečního stínu přesahující polovinu maximální šířky hrudníku (KTI > 0.50).",
    "src": "images/anki/cardiomegaly-3.jpg"
  },
  {
    "id": "atlas-extra-9",
    "questionId": "radio-35",
    "topicTitle": "Zobrazování ischemických CMP",
    "section": "Neuroradiologie a páteř",
    "category": "Neuroradiologie",
    "modality": "CT Iktový protokol",
    "title": "Akutní iktový algoritmus (CT + CTA + CTP)",
    "caption": "Moderní protokol zobrazování akutního mozkového infarktu pro indikaci trombolýzy a mechanické trombektomie.",
    "src": "images/anki/F4.large_1597975591721.jpg"
  },
  {
    "id": "atlas-extra-10",
    "questionId": "radio-4",
    "topicTitle": "Princip CT vyšetření",
    "section": "Obecná část a fyzika",
    "category": "Základy",
    "modality": "CT Fyzika",
    "title": "Hounsfieldovy jednotky (HU) stupnice denzit",
    "caption": "Denzity tkání na CT: vzduch (-1000 HU), tuk (-100 HU), voda (0 HU), měkké tkáně (+40 HU), kost (+1000 HU).",
    "src": "images/anki/paste-d7d5eb34458b8b45e0d74d31575b2d9686f2be44.jpg"
  },
  {
    "id": "atlas-extra-11",
    "questionId": "radio-48",
    "topicTitle": "Nevaskulární intervenční metody",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "Intervenční RTG",
    "title": "Perkutánní vertebroplastika",
    "caption": "Aplikace kostního cementu pod skiaskopickou navigací do těla obratle pro stabilizaci a úlevu od bolesti.",
    "src": "images/anki/percutaneous-vertebroplasty (1).jpg"
  },
  {
    "id": "atlas-extra-12",
    "questionId": "radio-44",
    "topicTitle": "Příprava nemocného před angiografií",
    "section": "Angiografie a intervence",
    "category": "Intervence & Cévy",
    "modality": "RTG Hrudník",
    "title": "Správná poloha PICC katetru v horní duté žíle (SVC)",
    "caption": "Skiagrafické ověření polohy hrotu centrálního žilního katetru v dolní třetině horní duté žíly.",
    "src": "images/anki/picc-line-2.jpg"
  }
];
